ORIG_DB_SERVER = 'localhost'
ORIG_DB_USER = 'panopticlick'
ORIG_DB_PASS = 'panopticlick'
ORIG_DB_NAME = 'panopticlick_orig'

DB_SERVER = 'localhost'
DB_USER = 'panopticlick'
DB_PASS = 'panopticlick'
DB_NAME = 'panopticlick'
TABLE_NAME = 'foo'